dependecies:
  - smartcontractkit/chainlink@1.10.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.10.0"
dotenv: .env

networks:
  default: development
  goerli:
    verify: true
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    chainlink_oracle: "0x99c3F6340B42B3E378f6f899ACD4f764c0cb54CC"
    job_id: "ec013753fda740f8bc74a966daea0723"
    api_key: ${API_KEY}

wallets:
  from_key: ${PRIVATE_KEY}
  from_key_2: ${PRIVATE_KEY_2}
