dependecies:
  - smartcontractkit/chainlink@1.10.0
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.10.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
dotenv: .env

networks:
  default: development
  goerli:
    verify: true
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    chainlink_oracle: "0xCC79157eb46F5624204f47AB42b3906cAA40eaB7"
    job_id: "ca98366cc7314957b8c012c72f05aeeb"
    api_key: ${API_KEY}

  development:
    api_key: ${API_KEY}

contracts:
  MockOracle:
    compiler: "0.6.0"
wallets:
  from_key: ${PRIVATE_KEY}
  from_key_2: ${PRIVATE_KEY_2}
